version: "3.8"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    env_file:
      - ./env/db.env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  web:
    build: .
    ports:
      - 8888:8888
    env_file:
      - ./env/web.env
    depends_on:
      - db
