version: "3.8"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: default_db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  web:
    build: .
    ports:
      - 8888:8888
    environment:
      PYTHONUNBUFFERED: 1
    depends_on:
      - db
